### ISSUE TITLE
RoR Recipes App - Kanban Board Setup 🎫

### ISSUE THREAD

**Issue by ITurres** [demesameneshoa/recipes-app#4]
## Hi there! We are @ITurres and @demesameneshoa,

- Team Member 1: @demesameneshoa .
- Team Member 2: @ITurres .

💎 [RoR Kanban Board](https://github.com/users/demesameneshoa/projects/2).

**Comment by danmainah** [comment]
Hi @ITurres and @demesameneshoa , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights


# Required Changes ♻️

- [ ] @Team Great work adding tasks on the Kanban board, however, the task below doesn't have a description and points of how many hours it takes to be accomplished, kindly consider adding a description to it or removing it from the kanban board..
![image](https://github.com/demesameneshoa/recipes-app/assets/61408860/3756b409-0d5f-4b28-8865-ce17a5f55f36)

- [ ] @Team great work adding a task to handle the N + 1 problem, however, you forgot to add a description dn also assign a member to this task
![image](https://github.com/demesameneshoa/recipes-app/assets/61408860/57a25cee-c646-4c79-9aa2-08322d5f738f)

- [ ] @Team Great work adding tests as part of the other tasks, however, each task should have its independent card, kindly consider adding one for the `Write unit and integration tests` task.
- [ ] Kindly consider adding specific points to the task below, all tasks should have a set timeline to be accomplished
![image](https://github.com/demesameneshoa/recipes-app/assets/61408860/ba91ac8f-7ce1-42bf-94ae-f10fdbdc150a)

- [ ] [optional] I would highly recommend rearranging your cards such that each card contains only requirements listed in the particular task

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

**Comment by ITurres** [comment]
### Hi @danmainah Daniel!, thank you for reviewing our Board.

A couple of things to highlight 🤠 

- The IMPORTANT and NOTES are not tickets/tasks to complete, they are just simple notes for the team to remember stuff.
- Regarding the `Unit and Integration tests`. They must go along with the feature being implemented on each ticket since working with TDD will require so.
- About the `Final touches` ticket, we haven't provided a specific time, since we do not know how long it might take. However, we will add a symbolic time for now.

---

#### Thank you for reviewing this PR. Feel free to reach out on Slack as _**Arturo (Arthur) Emanuel Guerra Iturres**_ and/or _**Demes Ameneshoa**_ for any queries or further assistance. 🌟

**Comment by danmainah** [comment]
@ITurres Thank you for the message, I understand your concern but these are project requirements 
![image](https://github.com/demesameneshoa/recipes-app/assets/61408860/bf19dfdc-e8d7-46d4-b7e3-bb4f7986fc51)

**Comment by ITurres** [comment]
@danmainah sure! We had given the `Final Touches` ticket an estimated time. 🤠

**Comment by Ghiftee** [comment]
## STATUS: APPROVED ♻️♻️
Hi @ITurres and @demesameneshoa , 

To highlight 👍🏽 
✔️ All tasks have a description and points
✔️ All tasks are assigned to a team member

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀  
Congratulations! 🎉 

![](https://user-images.githubusercontent.com/71140133/250156478-7da8ef4f-9230-4f28-951f-b0ea618e460d.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by ITurres** [comment]
Hi @Ghiftee, Thank you so much for having reviewed and approved our board! 🥂

**Comment by ITurres** [comment]
Hi @Ghiftee, Thank you so much for having reviewed and approved our board! 🥂
